language: python
dist: trusty
sudo: required
services:
  - docker
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - wget "http://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - docker pull jenkins/jenkins:lts
  - dockebuild -t jenkins .
  - docker run -p 8080:8080 -p 50000:50000 --env JAVA_OPTS="-Djenkins.install.runSetupWizard=false" jenkins
  - docker ps -a
install:
  - pip install -r requirements.txt
script:
  - pybot test.robot
notifications:
  email:
  - stollenwerk@kitconcept.com
